### ISSUE TITLE
Refresh Event Details in Database

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#162]
As a meetup admin, I want to be able to update event details on meetup and have them mirrored in our database.

Currently, we only add new events to the database, it would be nice to have functionality that allows us to refresh event details for events that have not occurred.

### Tasks

- [ ] check for deleted events
- [ ] rename task and task table to refer to all events, not just new events
- [ ] admin interface would be nice

### Resources

- [MetaData](https://docs.sqlalchemy.org/en/13/core/metadata.html) -- stores information about schema
- [Reflect table](https://docs.sqlalchemy.org/en/13/core/reflection.html) -- use metadata to find out table schema
- [Update in SQLAlchemy Core](https://docs.sqlalchemy.org/en/13/core/tutorial.html#inserts-updates-and-deletes)
