### ISSUE TITLE
Multitenancy

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#186]
#88 requires a lot more work to be done. In order to keep things structured, let's split into multiple epics, prioritize, and get things done as time permits.

We are currently able to install Busy Beaver in multiple workspaces, but only some features are enabled.

###  Progress

- [x] GitHub Summary Feature
  - [x] MVP (working in multiple workspaces + onboarding experience) -- #187 
  - [x] automate the creation of a job that posts daily summaries for each new workspace; currently, this is manually done... but we're in the beta phase
  - [x] add field that signals if feature enabled or not
- [x] Upcoming events -- spun out as #290
- [x] Retweeter -- feature has been deleted via #323 
- [x] Interface for workspace admins to configure settings -- spun out as #202
- [x] GitHub Webhook (no changes)
- [x] External integration (no changes)

### Things to think about

- [ ] uninstalling app, [`app_uninstall`](https://api.slack.com/events/app_uninstalled) -- spun out as #324
- [x] Add install button to `README.md`
- [ ] Slack app store  -- spun out #325

**Comment by alysivji** [comment]
This issue is complete. The items that are not complete have been spun out into their own tickets.
