### ISSUE TITLE
Technical Debt

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#188]
This is a catch-all for all technical debt related to Busy Beaver.

- [x] add unit tests around GitHub summary output feature
- [x] `github_summary_users` should have a FK relationship with `github_summary_config`, not `slack_installation`
- [x] clean up state machine and add unit tests around it
  - make end-to-end tests a bit less
  - use [sqlalchemy-fsm](https://github.com/VRGhost/sqlalchemy-fsm) or finite-state-machine instead of transitions
- [x] clean up `slack/event_subscription.py`; think of a clean way to dispatch-- #216

**Comment by BinSquare** [comment]
Can you clarify on the action to take up on clean up of slack/event_subscription.py?

**Comment by alysivji** [comment]
This got completed over the past couple of weeks as I was polishing the bot for our upcoming release.
