### ISSUE TITLE
Settings page for Slack workspace admins

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#202]
Spinning this out from #186.

As an admin, I would like to have an interface where I can configure settings for various features.

### Features Wish List

- [ ] login with Slack; only admins can access this screen
- [ ] toggle switch to enable features -- #89 
- [ ] leverage Flask and bootstrap

### Task List

- [ ] look at other slack apps to figure out what they do

**Comment by alysivji** [comment]
Superceeded by #258
