### ISSUE TITLE
Migrating to Kubernetes

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#246]
This issue has been created to group all Pull Requests that were made to get Busy Beaver migrated to Kubernetes.

Was tracking this on a piece of paper and a markdown document.

### Subissues

- [X] Do not require HTTPS on healthcheck endpoint (#235)
- [X] RQ cleanup work -- probe script and explicit queue name (#236)
- [X] Fix PR template and add info to changelog script (#237)
- [X] HOTFIX: correct queue name (#239)
- [X] Duplicate polling tasks as Flask CLI commands (#238)
- [X] Key Value Table requires workspace ID (#240)
- [X] post_upcoming_events task requires workspace ID (#241)
- [X] Kubernetes Staging Environment (#242)
- [X] HOTFIX: Log errors to Sentry (#243)
- [X] HOTFIX: Use attribute versus instance (#244)
- [X] Remove loggly handler (#245)
- [X] Setting up Kubernetes in Production (#247)
