### ISSUE TITLE
Kubernetes Cleanup Work

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#248]
There is some work related to cleaning up the codebase after migrating to Kubernetes. We had to do things a bit different to fit in with the Kubernetes way of doing things.

We have some code that is not being used. Might as well cleanup.

### Sub Tasks

- [x] need to delete unused code in the codebase
- [x] remove Ansible dependencies
- [ ] figure out an automated way to deploy via Helm
  - `helm upgrade busybeaver-production ./busybeaver/ -f values/production.yaml --set image.version=[version]`

**Comment by alysivji** [comment]
The last item here is to automate the Helm deploy. This work will be tracked in #261
