### ISSUE TITLE
Upcoming Events for all installations

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#290]
This issue will track all items related to updating the `Upcoming Events` feature to work for all Slack installations.

## Problem Description

Currently the Upcoming Events feature works for the Chicago Python workspace. With the recent addition of a Settings page, we can start to migrate our single workspace features to work across all installations.

Getting the Upcoming Events functionality working should be our next focus. User groups put on events and automating sharing will make life easy.

### Constraints

- integrate with just Meetup for now

### Requirements

- [x] users are able to select which Meetup groups they to capture events from
- [x] users are able to select what day of the week, what time, and in what happen announcements are made
  - for now do Monday morning at 9am local
  - number of posts to show in the weekly job
- [x] URL for image to display
- [x] `/busybeaver next` and `/busybeaver events` work for all workspaces

### Nice to Haves

- allow people to upload a logo
  - moved to self-contained task: #295 

### Steps

- [x] update models
- [x] update database sync jobs to link to slack installation
- [x] data migration to connect the dots for the new workflow
- [x] building front-end for folks to integrate the bot
  - this requires us to rethink how we onboard
- [ ] create management command to queue next day's event posting jobs; schedule via CRON
- [ ] `/busybeaver events` should use the config for # of events

### Things to Think About

- selecting channel(bot can be invited to multiple channels -- always show channels we can do things in)
- build a seamless integration with Meetup, but requires Meetup Pro
