### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#40]
As a developer, I want to have unit tests to help me ensure the program does what it intends to do.

Used end-to-end tests to find the best structure of the program; with this more or less settled, we should think about adding unit tests.

What is the best strategy is for testing this type of application?

### Subissues

- [x] [#109 Add tests for Slack Adapter](https://github.com/alysivji/busy-beaver/pull/109)
- [x] [#111 Add tests for background job + endpoint to kickoff GitHub Summary Post](https://github.com/alysivji/busy-beaver/pull/111)
- [x] Add tests around GitHub Summary generator

**Comment by alysivji** [comment]
I'm comfortable with the tests we have around our features.
